name: 'exp0_hparam'
project: 'SPC'
method: grid
metric:
  goal: maximize
  name: valid/avg_acc
program: main.py

parameters:
  dataset: 
    values: ["cifar100"]
  n_tasks:
    values: [20]
  n_epochs:
    values: [80, 100, 120]
  n_warmup_epochs:
    values: [20, 40]
  batch_size:
    values: [128]
  lr: 
    values: [0.01, 0.005]
  supcon_temperature:
    values: [0.1, 0.2, 0.3]

  # Setting
  method:
    value: "simclr"
  unsupervised:
    value: 0
  keep_training_data:
    value: 1
  use_augs:
    value: 1
  cuda_id:
    value: 0
  save_snapshot:
    value: 0
  use_snapshots:
    value: 0
  data_root:
    value: $SLURM_TMPDIR/cl-datasets/
  snapshot_path:
    value: $HOME/codes/lifelong-ssl/snapshots/

  model:
    value: "resnet18"
  nf:
    value: 64
  projection_size:
    value: 128
  projection_hidden_size:
    value: 512
  
  # Eval Settigns
  task_incremental:
    value: 1
  multilinear_eval:
    value: 1
  singlelinear_eval:
    value: 0
  cka_eval:
    value: 0
  
  # Defaults
  download:
    value: 1
  task_free: 
    value: 0
  wandb:
    value: 1
  wandb_mode:
    value: "offline"
  exp_name:
    value: "exp0_hparam"
